// Code generated by golangee/architecture. DO NOT EDIT.

// Package search contains all bounded domain API models, the according use cases and
// all other port and adapter implementations.
//
// This context is about everything around searching for books.
// A search can be issued from a users home or from within the library building by users or
// employees. It allows access to any known book, which may not be even available physically,
// like ebooks or new publications.
package search
