// Code generated by golangee/architecture. DO NOT EDIT.

package rest

import (
	httprouter "github.com/julienschmidt/httprouter"
	http "net/http"
)

// wrap converts from the http.HandlerFunc to the httprouter.Handle interface.
func wrap(route string, handler http.HandlerFunc) (string, httprouter.Handle) {
	return route, func(writer http.ResponseWriter, request *http.Request, _ httprouter.Params) {
		handler(writer, request)
	}
}
