// Code generated by golangee/architecture. DO NOT EDIT.

// Package rest contains the REST specific implementation for the current bounded context.
// It depends only from the use cases and transitively on the core API.
// The current api version is v1.0.1.
package rest
