// Code generated by golangee/architecture. DO NOT EDIT.

// Package security contains all bounded domain API models, the according use cases and
// all other port and adapter implementations.
//
// This context provides authentication (is a user the one he pretends to be?) and authorization (has a user a specific role or is allowed to access an un(!)specific resource?).
package security
