// Code generated by golangee/architecture. DO NOT EDIT.

// Package loan contains all bounded domain API models, the according use cases and
// all other port and adapter implementations.
//
// This context is about everything around loaning or renting a book.
// Only physical books can be loaned from within the library building by users.
package loan
