// Code generated by golangee/architecture. DO NOT EDIT.

package core

import (
	uuid "github.com/golangee/uuid"
)

// Book is a book with meta data to index and find.
type Book struct {
	// ID is the unique id of a book.
	ID uuid.UUID
	// Title is the title for the book.
	Title string
}

// BookRepository is a repository to handle books.
type BookRepository interface {
	// ReadAll returns all books.
	ReadAll() []Book
}
