// Code generated by golangee/architecture. DO NOT EDIT.

package core

// Opts is an option type for the factory.
type Opts struct {
	// Flag is for something.
	Flag bool
}

// NewSearchService is a factory to create a new SearchService.
//
// The parameter 'opts' contains options to configure the instance.
//
// The parameter 'repo' is the repo implementation to use.
//
// The result 'SearchService' is a package private instance.
func NewSearchService(opts Opts, repo BookRepository) SearchService {
	// this package private function is implemented by the developer
	return newSearchService(opts, repo)
}
