// Code generated by golangee/architecture. DO NOT EDIT.

package core

// SearchServiceFactory is the factory function to create a new instance of SearchService.
//
// The parameter 'opts' contains the options to create the instance.
//
// The parameter 'bookRepository' is a non-nil instance.
//
// The result 'SearchService' is the new instance or nil in case of an error.
//
// The result 'error' indicates a violation of pre- or invariants and represents an implementation specific failure.
var SearchServiceFactory = func(opts SearchServiceOpts, bookRepository BookRepository) (SearchService, error) {
	return &SearchServiceMock{}, nil
}

// SearchServiceOpts provides the options for creating a new instance of SearchService.
type SearchServiceOpts struct {
	// FulltextSearch is a flag to enable fulltext search in items.
	FulltextSearch bool `json:"full-text-SEARCH,omitempty" `
}
