// Code generated by golangee/architecture. DO NOT EDIT.

package core

import (
	context "context"
)

// SearchServiceMock is a mock implementation of SearchService.
// ...is the domain specific service API.
type SearchServiceMock struct {
	// SearchFunc mocks the Search function.
	SearchFunc func(ctx context.Context, query string) ([]Book, error)
}

// Search inspects each book for the key words.
//
// The parameter 'ctx' is the context to control timeouts and cancellations.
//
// The parameter 'query' contains the query to search for.
//
// The result '[]Book' is the list of found books.
//
// The result 'error' indicates a violation of pre- or invariants and represents an implementation specific failure.
func (m SearchServiceMock) Search(ctx context.Context, query string) ([]Book, error) {
	if m.SearchFunc != nil {
		return m.SearchFunc(ctx, query)
	}

	panic("mock not available: Search")
}
