// Code generated by golangee/architecture. DO NOT EDIT.

// Package usecase contains all domain specific use cases for the current bounded context.
// It contains an exposed public API to be imported by PRESENTATION layers.
// It provides a private implementation of the use cases accessible by factory functions.
package usecase
