// Code generated by golangee/eearc; DO NOT EDIT.
//
// Copyright 2021 Torben Schinke
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package buildinfo

var (
	// JobID is a unique build id. Usually taken from the CI_JOB_ID
	// environment variable at build time.
	JobID string = "unknown"

	// CommitTag usually refers to the VCS branch or tag name and is probably taken from the
	// CI_COMMIT_TAG environment variable at build time.
	CommitTag string = "unknown"

	// JobStartedAt is hopefully in RFC3339 format and is likely taken from
	// the environment variable CI_JOB_STARTED_AT at build time.
	JobStartedAt string = "unknown"

	// CommitSha refers to the VCS commit hash, probably taken from the
	// CI_COMMIT_SHA environment variable at build time.
	CommitSha string = "unknown"

	// Host refers to the building host name, probably copied form the
	// CI_SERVER_HOST environment variable at build time.
	Host string = "unknown"
)

// buildInfo is a private type to allow an interface based access to the environment variables.
type buildInfo struct{}

// ID returns the current BuildID.
func (_ buildInfo) ID() string {
	return JobID
}

// Tag returns the current BuildTag.
func (_ buildInfo) Tag() string {
	return CommitTag
}

// Build provides the build information about the application.
var Build buildInfo
