// Code generated by golangee/eearc; DO NOT EDIT.
//
// Copyright 2021 Torben Schinke
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package buildinfo

var (
	// BuildID is usually a strict monotonic increasing build number.
	BuildID string = "unknown"

	// BuildTag usually refers to the VCS branch or tag name.
	BuildTag string = "unknown"
)

// buildInfo is a private type to allow an interface based access to the environment variables.
type buildInfo struct{}

// ID returns the current BuildID.
func (_ buildInfo) ID() string {
	return BuildID
}

// Tag returns the current BuildTag.
func (_ buildInfo) Tag() string {
	return BuildTag
}

// Build provides the build information about the application.
var Build buildInfo
