// Code generated by golangee/architecture. DO NOT EDIT.

package application

import (
	loancore "example-server/internal/loan/core"
	loanusecase "example-server/internal/loan/usecase"
	core "example-server/internal/search/core"
	mysql "example-server/internal/search/mysql"
	usecase "example-server/internal/search/usecase"
)

// Options represents the uber options and bundles all options from all
// bounded contexts and layers in one monolithic instance.
type Options struct {
	SearchMysqlOptions          mysql.Options
	SearchCoreSearchServiceOpts core.SearchServiceOpts
	SearchUsecaseBookSearchOpts usecase.BookSearchOpts
	LoanCoreLoanServiceOpts     loancore.LoanServiceOpts
	LoanUsecaseBookLoaningOpts  loanusecase.BookLoaningOpts
}

// Reset restores all default values.
func (o *Options) Reset() {
	o.SearchMysqlOptions.Reset()
	o.SearchCoreSearchServiceOpts.Reset()
	o.SearchUsecaseBookSearchOpts.Reset()
	o.LoanCoreLoanServiceOpts.Reset()
	o.LoanUsecaseBookLoaningOpts.Reset()
}

// ParseEnv parses values from the environment.
func (o *Options) ParseEnv() error {
	if err := o.SearchMysqlOptions.ParseEnv(); err != nil {
		return err
	}

	if err := o.SearchCoreSearchServiceOpts.ParseEnv(); err != nil {
		return err
	}

	if err := o.SearchUsecaseBookSearchOpts.ParseEnv(); err != nil {
		return err
	}

	if err := o.LoanCoreLoanServiceOpts.ParseEnv(); err != nil {
		return err
	}

	if err := o.LoanUsecaseBookLoaningOpts.ParseEnv(); err != nil {
		return err
	}

	return nil
}

// ConfigureFlags configures the flag package to receive parsed flags.
func (o *Options) ConfigureFlags() {
	o.SearchMysqlOptions.ConfigureFlags()
	o.SearchCoreSearchServiceOpts.ConfigureFlags()
	o.SearchUsecaseBookSearchOpts.ConfigureFlags()
	o.LoanCoreLoanServiceOpts.ConfigureFlags()
	o.LoanUsecaseBookLoaningOpts.ConfigureFlags()
}
