// Code generated by golangee/architecture. DO NOT EDIT.

package application

import (
	loancore "example-server/internal/loan/core"
	core "example-server/internal/search/core"
)

// Options represents the uber options and bundles all options from all
// bounded contexts and layers in one monolithic instance.
type Options struct {
	SearchCoreSearchServiceOpts core.SearchServiceOpts
	LoanCoreLoanServiceOpts     loancore.LoanServiceOpts
}

// Reset restores all default values.
func (o *Options) Reset() {
	o.SearchCoreSearchServiceOpts.Reset()
	o.LoanCoreLoanServiceOpts.Reset()
}

// ParseEnv parses values from the environment.
func (o *Options) ParseEnv() error {
	if err := o.SearchCoreSearchServiceOpts.ParseEnv(); err != nil {
		return err
	}

	if err := o.LoanCoreLoanServiceOpts.ParseEnv(); err != nil {
		return err
	}

	return nil
}

// ConfigureFlags configures the flag package to receive parsed flags.
func (o *Options) ConfigureFlags() {
	o.SearchCoreSearchServiceOpts.ConfigureFlags()
	o.LoanCoreLoanServiceOpts.ConfigureFlags()
}
