// Code generated by golangee/architecture. DO NOT EDIT.

// Package core contains all domain specific models for the current bounded context.
// It contains an exposed public API to be imported by other layers and an internal package
// private implementation accessible by factory functions.
package core
