// Code generated by golangee/architecture. DO NOT EDIT.

// Package main contains the executable to launch the actual BookLibrary server process.
package main

import (
	application "example-server/internal/application"
	log "log"
)

func main() {
	a, err := application.NewApp()
	if err != nil {
		log.Fatal(err)
	}

	if err := a.Start(); err != nil {
		log.Fatal(err)
	}
}
